algoritmo "aula19_3"
// F9 (executa meu código)

// Autor : Danielli
// Data : 14/04/2026

var
//Variaveis
           esgotado, n, s: literal
inicio
// Comandos
   escreva ("O produto está esgotado? (s/n) ")
   leia (esgotado)

   se (esgotado = "n") entao
   escreval ("Produto disponível para venda")
   senao
   escreval ("Por favor, reabasteça o estoque")
   fimse
fimalgoritmo
