algoritmo "semnome"
// F9 (Executa meu código)
// Autor :Ana Julia
// Data : 14/04/2026
// Seção de Declarações 
var
//variaveis
javascript, python: literal
idade: real

inicio
// Seção de Comandos
escreva ("insira sua idade: ")
leia (idade)


escreva ("voce sabe javascript? (s/n): ")
leia (javascript)

escreva ("voce sabe python? (s/n): ")
leia (python)

se ((idade >= 18) e ((javascript = "s") ou (python = "s"))) entao
escreval ("o curriculo sera aceito")
senao
escreval ("o curriculo foi recusado")
fimse





fimalgoritmo
