algoritmo "nota"
// F9: (Executa meu código)
// Autor :Ana Julia
// Data : 14/04/2026
// Seção de Declarações 
var
//variaveis
nota, frequencia: real
aprovado, reprovado: literal

inicio
// Seção de Comandos 
escreva ("Digite a nota: ")
leia (nota)
escreva ("Digite a frequencia: ")
leia (frequencia)
se (nota <7) e (frequencia < 75) entao
escreval ("o aluno foi reprovado")
senao
se (nota >=7)e (frequencia >= 75) entao
escreval ("o aluno foi aprovado")
fimse
fimse

fimalgoritmo
