algoritmo "produto esgotado"
// F9 (Executa meu código)
// Autor :Ana Julia
// Data : 14/04/2026
// Seção de Declarações 
var
//variaveis
esgotado, naoesgotado: literal


inicio
// Seção de Comandos
escreva ("o produto esta esgotado? (s/n)  ")
leia (esgotado)
se (esgotado = "n" ) entao
escreval ("Produto disponivel para venda")
senao
escreval ("Por favor, reabasteça o estoque")
fimse

fimalgoritmo
